package io.github.markpollack.harness.flows.workflow;

import java.util.Objects;

/**
 * A directed edge in the {@link WorkflowGraph} intermediate representation.
 * <p>
 * Edges connect nodes and carry a typed {@link EdgeCondition} (never null).
 * An optional human-readable label aids visualization and trace output.
 * <p>
 * Edges are auto-generated by the DSL — developers never write edges directly.
 *
 * @param from      the source node name
 * @param to        the target node name
 * @param condition typed routing condition (never null)
 * @param label     human-readable label for visualization (may be null)
 */
public record WorkflowEdge(
        String from,
        String to,
        EdgeCondition condition,
        String label
) {

    public WorkflowEdge {
        Objects.requireNonNull(from, "from must not be null");
        Objects.requireNonNull(to, "to must not be null");
        Objects.requireNonNull(condition, "condition must not be null");
    }

    // -- Factory methods --

    /** Creates an unconditional (sequential) edge. */
    public static WorkflowEdge sequence(String from, String to) {
        return new WorkflowEdge(from, to, new EdgeCondition.Unconditional(), null);
    }

    /** Creates a conditional edge with a label. */
    public static WorkflowEdge conditional(String from, String to, EdgeCondition condition, String label) {
        return new WorkflowEdge(from, to, condition, label);
    }

    // -- Backward-compat factory methods (used by existing tests) --

    /** Creates an unconditional edge (alias for sequence). */
    public static WorkflowEdge of(String from, String to) {
        return sequence(from, to);
    }

    /** Creates a labeled unconditional edge. */
    public static WorkflowEdge labeled(String from, String to, String label) {
        return new WorkflowEdge(from, to, new EdgeCondition.Unconditional(), label);
    }

    /** Returns true if this edge is unconditional (always taken). */
    public boolean isUnconditional() {
        return condition instanceof EdgeCondition.Unconditional;
    }
}
