/*
 * Copyright 2024-2026 Mark Pollack
 *
 * Licensed under the Business Source License 1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://mariadb.com/bsl11/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.markpollack.harness.flows.workflow;

import io.github.markpollack.harness.patterns.graph.NodeMetrics;

import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * The compiled intermediate representation of a workflow.
 * <p>
 * {@code WorkflowGraph} is a pure data structure — no execution logic, no
 * Spring AI dependencies. The DSL builds it; the {@code WorkflowExecutor}
 * runs it; the {@code TraceRecorder} reads it.
 * <p>
 * Having an independent IR enables replay, visualization, and Markov analysis
 * without coupling to the execution engine.
 *
 * @param name       the workflow identifier
 * @param nodes      ordered list of workflow nodes
 * @param edges      routing edges (auto-generated by DSL, never user-written)
 * @param startNode  the name of the first node to execute
 * @param finishNode the name of the final node
 * @param metrics    per-node execution metrics (empty until populated post-run)
 * @param <I>        the workflow input type
 * @param <O>        the workflow output type
 */
public record WorkflowGraph<I, O>(
        String name,
        List<WorkflowNode> nodes,
        List<WorkflowEdge> edges,
        String startNode,
        String finishNode,
        Map<String, NodeMetrics> metrics
) {

    /**
     * Canonical constructor — normalizes to unmodifiable views.
     */
    public WorkflowGraph {
        Objects.requireNonNull(name, "name must not be null");
        nodes = List.copyOf(nodes);
        edges = List.copyOf(edges);
        Objects.requireNonNull(startNode, "startNode must not be null");
        Objects.requireNonNull(finishNode, "finishNode must not be null");
        metrics = Map.copyOf(metrics);
    }

    /**
     * Creates a WorkflowGraph with empty metrics.
     *
     * @param name       the workflow identifier
     * @param nodes      ordered list of workflow nodes
     * @param edges      routing edges
     * @param startNode  the first node name
     * @param finishNode the final node name
     * @param <I>        input type
     * @param <O>        output type
     * @return a new WorkflowGraph
     */
    public static <I, O> WorkflowGraph<I, O> of(
            String name,
            List<WorkflowNode> nodes,
            List<WorkflowEdge> edges,
            String startNode,
            String finishNode) {
        return new WorkflowGraph<>(name, nodes, edges, startNode, finishNode, Map.of());
    }

    /**
     * Returns a new graph with the given metrics — the original is unchanged.
     * <p>
     * Called by {@code WorkflowExecutor} after execution to enrich the graph
     * with per-node timing, token, and cost data.
     *
     * @param metrics per-node execution metrics keyed by node name
     * @return a new WorkflowGraph with metrics populated
     */
    public WorkflowGraph<I, O> withMetrics(Map<String, NodeMetrics> metrics) {
        return new WorkflowGraph<>(name, nodes, edges, startNode, finishNode, metrics);
    }

    /**
     * Finds a node by name.
     *
     * @param nodeName the node name
     * @return the node, or empty if not found
     */
    public Optional<WorkflowNode> findNode(String nodeName) {
        return nodes.stream()
                .filter(n -> n.name().equals(nodeName))
                .findFirst();
    }

    /**
     * Returns the edges originating from the given node.
     *
     * @param nodeName the source node name
     * @return list of outgoing edges (may be empty)
     */
    public List<WorkflowEdge> edgesFrom(String nodeName) {
        return edges.stream()
                .filter(e -> e.from().equals(nodeName))
                .toList();
    }
}
