/*
 * Copyright 2024-2026 Mark Pollack
 *
 * Licensed under the Business Source License 1.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://mariadb.com/bsl11/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.markpollack.harness.flows.workflow;

import java.util.Objects;
import java.util.function.Function;
import java.util.function.Predicate;

/**
 * A directed edge in the {@link WorkflowGraph} intermediate representation.
 * <p>
 * Edges connect nodes and optionally carry a condition (for branching)
 * and a transform function (for type adaptation between steps).
 * <p>
 * Edges are auto-generated by the DSL — developers never write edges directly.
 * The {@code WorkflowExecutor} evaluates conditions at runtime to determine routing.
 *
 * @param from      the source node name
 * @param to        the target node name
 * @param condition routing predicate (null = unconditional)
 * @param transform output transformation (null = identity/pass-through)
 * @param label     human-readable label for visualization (null = none)
 */
public record WorkflowEdge(
        String from,
        String to,
        Predicate<Object> condition,
        Function<Object, Object> transform,
        String label
) {

    public WorkflowEdge {
        Objects.requireNonNull(from, "from must not be null");
        Objects.requireNonNull(to, "to must not be null");
    }

    /**
     * Creates an unconditional edge.
     *
     * @param from the source node name
     * @param to   the target node name
     * @return a new unconditional edge
     */
    public static WorkflowEdge of(String from, String to) {
        return new WorkflowEdge(from, to, null, null, null);
    }

    /**
     * Creates a conditional edge.
     *
     * @param from      the source node name
     * @param to        the target node name
     * @param condition the routing predicate
     * @return a new conditional edge
     */
    public static WorkflowEdge conditional(String from, String to, Predicate<Object> condition) {
        return new WorkflowEdge(from, to, condition, null, null);
    }

    /**
     * Creates a labeled unconditional edge (for visualization).
     *
     * @param from  the source node name
     * @param to    the target node name
     * @param label the edge label
     * @return a new labeled edge
     */
    public static WorkflowEdge labeled(String from, String to, String label) {
        return new WorkflowEdge(from, to, null, null, label);
    }

    /**
     * Returns true if this edge is unconditional (always taken).
     *
     * @return true if no condition is set
     */
    public boolean isUnconditional() {
        return condition == null;
    }

    /**
     * Tests whether this edge should be taken given the current output.
     * Unconditional edges always return true.
     *
     * @param output the output from the source node
     * @return true if this edge matches
     */
    public boolean matches(Object output) {
        return condition == null || condition.test(output);
    }
}
